### ISSUE TITLE
Previous word disappears with merging

### ISSUE THREAD

**Issue by verbruggenh** [ereadingtool/ereadingtool#24] opened 2019-06-07 17:47 UTC
This issue is related to issue #13, but slightly different.

In the third paragraph of text 82 "Recollections of Maria Pogrebova", when I tried to merge "потому что", the "что" from earlier in the paragraph (directly before "нужно") disappeared, and the merging did not work. 

I think this has happened in other texts to, because I have seen the paragraph where the merge is happening jump in a strange way after a merge sometimes, and now I think that jump was a word disappearing. I just don't remember which texts have been affected.

**Comment by andrew-silvernail** [comment] 2019-06-12 01:01
@verbruggenh this seems to have the same root cause as #13 .

**Comment by andrew-silvernail** [comment] 2019-08-20 01:34
Fixed in PR  #38.

**Closed by andrew-silvernail** 2019-08-20 01:34 UTC
Labels: bug, translations
