### ISSUE TITLE
Enhance the difficulty selection on the page for finding texts to read.

### ISSUE THREAD

**Issue by andrew-silvernail** [ereadingtool/ereadingtool#53] opened 2020-04-10 03:12 UTC
From a stakeholder:

'Under “Difficulty” the website highlights the difficulty that I have chosen. I found it misleading that you can then click on a different difficulty level that would then highlight, but the texts shown below would not change. I realized that I had to go back to the home dashboard to change my text difficulty. It would be nice if this were available in both places, but if not, at least it should be changed so that the highlighted difficulty does not appear to change on the page, while the choice of texts actually remains the same.'

**Comment by bgins** [comment] 2020-10-07 16:55
Unable to reproduce in production or local development. It may be that latency prevented the results from updating in a reasonable amount of time.

**Comment by wcomer** [comment] 2020-10-30 18:59
Bill:
On the current in production site, on the page where you pick a text, you can actually highlight two difficulty levels, and then no texts appear (which makes sense since no text has both difficulty levels associated with it).
Having the difficulty level selection be mutually exclusive would help.

On the local development site, you similarly seem to be able to highlight two difficulty levels at the same time (at least on desktop versions)
It seemed for a moment that if you highlighted two contiguous difficulty levels you could get both sets of responses. Non-contiguous highlights seemed to bring up the lowest difficulty level.  
And then in all my clicking I broke it ("An error occurred. Please contact an administrator").  Can't tell whether that broke it or the fact that I was logged in both on mobile and on desktop at the same time.

**Comment by wcomer** [comment] 2020-10-30 19:10
To follow up... I think the error message was coming from the fact that I was logged in to two different instances of the website on different platforms. Closing one and restarting on my mobile device the site worked again.

**Comment by bgins** [comment] 2020-10-30 22:23
Thanks for the details on this one. Selecting multiple difficulties could mean "show me the texts at all selected difficulty levels", though I am not sure if that is what we actually do at the moment.

Mutually exclusive does seem more intuitive because students will want to target a difficulty level.

**Closed** 2020-11-09 16:21 UTC
Labels: enhancement, student, text search
