### ISSUE TITLE
Possible problem with resetting password

### ISSUE THREAD

**Issue by verbruggenh** [ereadingtool/ereadingtool#26] opened 2019-06-11 21:19 UTC
One of the UCLA folks reported that when she tried to retrieve her password, she got the following message:
Oops! Something went wrong when starting your Elm program.
Trying to initialize the `Main` module with an unexpected flag.
I tried to convert it to an Elm value, but ran into this problem:

Expecting an object with a field named `forgot_pass_endpoint` but instead got: {"csrftoken":"IFOijmf06F2U3PklXZ9Ouo4Gz6rvJrDr7EqhH68BUrwvSfnTWLwBFRjA8rGz3OGt"}

She wasn't clear about if she was trying to retrieve a password for a student or instructor account, and she didn't mention where in the process she received that message.

I tried to reset the password on one of my accounts a few minutes ago, but after putting the email address in the box, I still have not received anything, so I don't think the email to reset the password is sending.

**Comment by andrew-silvernail** [comment] 2019-06-12 00:52
> One of the UCLA folks reported that when she tried to retrieve her password, she got the following message:
> Oops! Something went wrong when starting your Elm program.
> Trying to initialize the `Main` module with an unexpected flag.
> I tried to convert it to an Elm value, but ran into this problem:
> 
> Expecting an object with a field named `forgot_pass_endpoint` but instead got: {"csrftoken":"IFOijmf06F2U3PklXZ9Ouo4Gz6rvJrDr7EqhH68BUrwvSfnTWLwBFRjA8rGz3OGt"}
> 
> She wasn't clear about if she was trying to retrieve a password for a student or instructor account, and she didn't mention where in the process she received that message.
> 
> I tried to reset the password on one of my accounts a few minutes ago, but after putting the email address in the box, I still have not received anything, so I don't think the email to reset the password is sending.

RE: The Elm flag error, I know this was an issue in the past, but I can't reproduce it now ([https://stepstoadvancedreading.org/user/password_reset/](https://stepstoadvancedreading.org/user/password_reset/ ) is working for me).  Let me know which link to take a look at.

For the password reset I'll give it a try and see what happens with SendGrid.  Thanks for the help!

**Comment by andrew-silvernail** [comment] 2019-08-20 02:04
Fixed in PR #39 .

**Closed by andrew-silvernail** 2019-08-20 02:04 UTC
Labels: accounts, bug
