### ISSUE TITLE
Words disappear with merging

### ISSUE THREAD

**Issue by verbruggenh** [ereadingtool/ereadingtool#13] opened 2019-06-04 17:29 UTC
In the final paragraph of text 52 "Water Contaminants", "и т.д." partially disappeared when I tried merging. The section, which should read as "железо и т. д.," now reads as "железо. д.,".

In the second paragraph of text 21 "Lyudmila Gurchenko's Daughter", "помощь" disappeared when I tried to merge "скорая помощь".

About two-thirds through text 74 "Vocal Group Pyatero", "основном" disappeared when I tried to merge "в основном".

In text 75 "Beautiful People", "что" disappeared when I tried to merge "потому что".

In text 77 "Theresa May and Margaret Thatcher", "тем" disappeared when I tried to merge "тем не менее".

**Comment by andrew-silvernail** [comment] 2019-06-08 21:07
Found an ordering issue on the backend.  Wrote a fix and regression test on #25 .

**Comment by andrew-silvernail** [comment] 2019-06-11 01:14
@verbruggenh I've pushed a fix for this and deleted the word groups associated with text ids you gave me.  I'll leave this ticket open until we've confirmed everything is good.

**Comment by verbruggenh** [comment] 2019-06-11 20:39
@andrew-silvernail Another one I noticed but didn't put here was the third paragraph of text 82 "Recollections of Maria Pogrebova". When I tried to merge "потому что", the "что" disappeared. 

Will the fixed you pushed prevent words from disappearing when I try to merge them? If it does, then I'll start merging things again, but if not, I don't want to merge again until that's resolved.

Also, I'm worried there might have been other instances of words disappearing in a merge that I missed, because it's sometimes hard to catch. I think I'm going to have to manually go through and compare them (unless you can think of a better option), and then I'll get back to you with any other missing words I might find. Thanks!

**Comment by andrew-silvernail** [comment] 2019-06-12 00:45
@verbruggenh, my responses are below.

> Another one I noticed but didn't put here was the third paragraph of text 82 "Recollections of Maria Pogrebova". When I tried to merge "потому что", the "что" disappeared.

Okay.  I've deleted the one grouping from the system that was backwards.  Give it a try now.

> Will the fixed you pushed prevent words from disappearing when I try to merge them?

My tests seem to indicate it will work now, but please let me know of exceptions!  Thanks for your help.

> Also, I'm worried there might have been other instances of words disappearing in a merge that I missed, because it's sometimes hard to catch. I think I'm going to have to manually go through and compare them (unless you can think of a better option), and then I'll get back to you with any other missing words I might find. Thanks!

One low-hanging solution to this is to give you access to the Django admin page (if you don't already have it).  I can add the objects in question (TextWordGroups) to the admin and you can browse word groupings in the database at your leisure and delete/edit ones that don't make sense.  Let me know if you'd like to do that, we can create a feature ticket and work on it.

**Comment by verbruggenh** [comment] 2019-06-14 18:26
I'm currently working on seeing if the merging will work. I found a failed merging that I missed earlier. In the first paragraph of text 33 "Catastrophic Beginning", I tried to merge "и. т. д.,", and everything disappeared except for the д.

**Comment by andrew-silvernail** [comment] 2019-06-18 01:04
@verbruggenh : Thanks for testing.  Results of my tests are below.

For the merging in : 

- text 52, I get the same error.  Punctuation is a special case we never really considered, so I'll need more time on this one.
- text 21, seems to be fixed.
- text 74, I'm able to merge both words, but the UI doesn't seem to reflect their merged state until after I refresh the page.  This probably due to improper recording of which instance of 'в' we want to merge.
- text 75, seems to be fixed.
- text 77, merges improperly with disappearing words.  This is also likely due to improperly recording which instance of 'не' we want.

I'm going to leave this ticket open while I work out:

1. Properly recording the word instance for merges.
2. Including punctuation as possible mergeable 'words'.

**Comment by andrew-silvernail** [comment] 2019-06-19 00:39
@verbruggenh 

Update on text 77: I ran this merge on my local machine and discovered that the particular instance of 'не' we are merging is not a text word, so we run into trouble with that since we haven't decided on how to handle merging words that aren't already translated words.

We can handle this in a few ways, let me know which way you and Bill think is best (I'm guessing we'll want the second option):

1. Force the instructor to first tag the word as a text word before merging.
2. Have the UI first add the word as a text word and then immediately merge it.

I don't think they'll be any issues for option 2.  I can write a test.  Let me know.

**Comment by verbruggenh** [comment] 2019-06-19 23:16
I think option 2 will be our best bet. It is strange that the не is not
being recognized as a text word. I've noticed that that has happened to
random words in some places, and I'm not sure why. It is also what is
happening with the punctuation issues.

Thanks for working on this! It will be good to have the capability to merge
words without worrying that they will go away. I'll keep my eyes open for
any other issues.

**Comment by wcomer** [comment] 2020-10-30 18:34
Text issues:
https://stepstoadvancedreading.org/admin/text/220/

The funkiness of punctuation around merged words still seems a problem.
At the end of first paragraph I tried to merge арт-пространствах at the end of this first paragraph, the space between различных and арт disappears

When you go into the student view it also has disappeared. I can't add an additional space in the "edit" view and get it to stick.

If you try to fix this, you can test out your fix since there's another hyphenated word at the end of the next paragraph in the same text.

**Comment by bgins** [comment] 2021-01-06 16:23
With the changes in #300, all of the texts mentioned in this issue preserve all words and merge them correctly.

The one exception is in text 33 where "т. д." is already a compound word and cannot be merged with "и" to form "и т. д.". This appears to be a separate issue with merging. Will investigate it.

**Closed** 2021-02-26 23:21 UTC
Labels: bug, translations
